/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkkp;

/**
 *
 * @author timot
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        setTitle("Menu PKKP");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnPeserta = new javax.swing.JMenuItem();
        mnUser = new javax.swing.JMenuItem();
        mnKota = new javax.swing.JMenuItem();
        mnKel = new javax.swing.JMenuItem();
        mnKec = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnKeluar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnAdmin = new javax.swing.JMenuItem();
        mnTes = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        lapPeserta = new javax.swing.JMenuItem();
        lapAdmin = new javax.swing.JMenuItem();
        mnNilai = new javax.swing.JMenuItem();
        mnLolos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnexit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Data Master");

        mnPeserta.setText("Data Peserta");
        mnPeserta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPesertaActionPerformed(evt);
            }
        });
        jMenu1.add(mnPeserta);

        mnUser.setText("Data User");
        mnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUserActionPerformed(evt);
            }
        });
        jMenu1.add(mnUser);

        mnKota.setText("Data Kabupaten/Kota");
        mnKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKotaActionPerformed(evt);
            }
        });
        jMenu1.add(mnKota);

        mnKel.setText("Data Kelurahan");
        mnKel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKelActionPerformed(evt);
            }
        });
        jMenu1.add(mnKel);

        mnKec.setText("Data Kecamatan");
        mnKec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKecActionPerformed(evt);
            }
        });
        jMenu1.add(mnKec);
        jMenu1.add(jSeparator1);

        mnKeluar.setText("Keluar");
        mnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKeluarActionPerformed(evt);
            }
        });
        jMenu1.add(mnKeluar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaksi");

        mnAdmin.setText("Transaksi Administrasi");
        mnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAdminActionPerformed(evt);
            }
        });
        jMenu2.add(mnAdmin);

        mnTes.setText("Transaksi Tes Tertulis & Wawancara");
        mnTes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTesActionPerformed(evt);
            }
        });
        jMenu2.add(mnTes);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Laporan");

        lapPeserta.setText("Laporan Peserta");
        lapPeserta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapPesertaActionPerformed(evt);
            }
        });
        jMenu3.add(lapPeserta);

        lapAdmin.setText("Laporan Administrasi");
        lapAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapAdminActionPerformed(evt);
            }
        });
        jMenu3.add(lapAdmin);

        mnNilai.setText("Laporan Nilai");
        mnNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNilaiActionPerformed(evt);
            }
        });
        jMenu3.add(mnNilai);

        mnLolos.setText("Laporan Peserta Lolos");
        mnLolos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLolosActionPerformed(evt);
            }
        });
        jMenu3.add(mnLolos);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Utility");

        mnexit.setText("Keluar");
        mnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnexitActionPerformed(evt);
            }
        });
        jMenu4.add(mnexit);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUserActionPerformed
        // TODO add your handling code here:
        new DataUser().setVisible(true);
    }//GEN-LAST:event_mnUserActionPerformed

    private void mnKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKotaActionPerformed
        // TODO add your handling code here:
        new DataKota().setVisible(true);
    }//GEN-LAST:event_mnKotaActionPerformed

    private void mnPesertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPesertaActionPerformed
        // TODO add your handling code here:
        new DataPeserta().setVisible(true);
    }//GEN-LAST:event_mnPesertaActionPerformed

    private void mnKelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKelActionPerformed
        // TODO add your handling code here:
        new DataKelurahan().setVisible(true);
    }//GEN-LAST:event_mnKelActionPerformed

    private void mnKecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKecActionPerformed
        // TODO add your handling code here:
        new DataKecamatan().setVisible(true);
    }//GEN-LAST:event_mnKecActionPerformed

    private void mnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnKeluarActionPerformed

    private void mnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAdminActionPerformed
        // TODO add your handling code here:
        new Administrasi().setVisible(true);
    }//GEN-LAST:event_mnAdminActionPerformed

    private void mnTesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTesActionPerformed
        // TODO add your handling code here:
        new TransaksiTes().setVisible(true);
    }//GEN-LAST:event_mnTesActionPerformed

    private void lapPesertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapPesertaActionPerformed
        // TODO add your handling code here:
        new LapPeserta().setVisible(true);
    }//GEN-LAST:event_lapPesertaActionPerformed

    private void lapAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapAdminActionPerformed
        // TODO add your handling code here:
        new LapAdmin().setVisible(true);
    }//GEN-LAST:event_lapAdminActionPerformed

    private void mnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnexitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_mnexitActionPerformed

    private void mnNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNilaiActionPerformed
        // TODO add your handling code here:
        new LapNilai().setVisible(true);
    }//GEN-LAST:event_mnNilaiActionPerformed

    private void mnLolosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLolosActionPerformed
        // TODO add your handling code here:
        new LapPesertaLolos().setVisible(true);
    }//GEN-LAST:event_mnLolosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem lapAdmin;
    private javax.swing.JMenuItem lapPeserta;
    private javax.swing.JMenuItem mnAdmin;
    private javax.swing.JMenuItem mnKec;
    private javax.swing.JMenuItem mnKel;
    private javax.swing.JMenuItem mnKeluar;
    private javax.swing.JMenuItem mnKota;
    private javax.swing.JMenuItem mnLolos;
    private javax.swing.JMenuItem mnNilai;
    private javax.swing.JMenuItem mnPeserta;
    private javax.swing.JMenuItem mnTes;
    private javax.swing.JMenuItem mnUser;
    private javax.swing.JMenuItem mnexit;
    // End of variables declaration//GEN-END:variables
}
